---
include:
  # Standard split (left as central)
  - board: xiao_ble
    shield: forager_left rgbled_adapter
    snippet: softdevice-controller
  - board: xiao_ble
    shield: forager_right rgbled_adapter

  # Utility
  - board: xiao_ble
    shield: settings_reset
