---
include:
  # Standard split (left as central)
  - board: xiao_ble//zmk
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: forager_right rgbled_adapter

  # Dongle mode (dongle as central)
  - board: xiao_ble//zmk
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: forager_dongle-xiao_ble
  - board: xiao_ble//zmk
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC=n -DCONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
    artifact-name: forager_dongle-xiao_ble-radii
  - board: xiao_ble//zmk
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC=n -DCONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
    artifact-name: forager_dongle-xiao_ble-field
  - board: xiao_ble//zmk
    shield: forager_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_PROSPECTOR_STATUS_SCREEN_CLASSIC=n -DCONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
    artifact-name: forager_dongle-xiao_ble-operator
  - board: xiao_ble//zmk
    shield: forager_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n  # set left to peripheral
    artifact-name: forager_left-xiao_ble-dongle
  - board: xiao_ble//zmk
    shield: forager_right rgbled_adapter
    artifact-name: forager_right-xiao_ble-dongle

  # Utility
  - board: xiao_ble//zmk
    shield: settings_reset
